### PR TITLE
Handle resetting of connection

### LINKED ISSUE #65: Catch connection errors
When GitLab is down, one may see the following:

```
adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

It seems that this should be caught at `requests.get()`. Maybe it should be treated differently depending on the error code.

### PR DESCRIPTION
**Pull request by Simon-1-1**
Handle connection reset exception from requests.

Closes #65

### CODE REVIEW

**Comment by Simon-1-1** [comment]
Maybe necessary to catch MaxRetryError (urllib3) or ConnectTimeoutError also.

**Comment by Simon-1-1** [comment]
# Test

I have performed three manual tests for this PR.

## Non-existent domain

Put a domain that doesn't exist as the `api_url` in settings. Result:

```console
$ poetry run reviewcheck
Reviewcheck encountered a problem: There was an issue connecting to GitLab. Failed GET nonexistingwebpage6893872.com/api/v4/projects/1/merge_requests?state=opened&per_page=500
```

## Correct domain name, but wrong API base path

Put a working domain for GitLab as `api_url` but add a page that is not the API
base path at the end of it. Result:

```console
$ poetry run reviewcheck
Reviewcheck encountered a problem: Could not decode JSON. API endpoint might be wrong: https://<REDACTED>/nottheapi/api/v4
```

## Correct domain and API base path but wrong resource path

Add a project ID that doesn't exist to the configuration. Result:

```console
$ poetry run reviewcheck
Reviewcheck encountered a problem: Non-OK HTTP response from GitLab: '404 Client Error: Not Found for url: https://<REDACTED>/api/v4/projects/1000/merge_requests?state=opened&per_page=500'
```

**Review by mcantimu — APPROVED** [review]
Looks good

**Review by hdeknach — APPROVED** [review]
Looks great! Nice tests, useful when setting up reviewcheck.

**Pull request merged**
